const char HTTP_SCRIPT_CHART[] PROGMEM =
  "var dataPlot;"
  "var maxDataPoints = 20;"
  "function removeData(){"
    "dataPlot.data.labels.shift();"
    "dataPlot.data.datasets[0].data.shift();"
  "}"
  "function addData(label, data){"
    "if(dataPlot.data.labels.length > maxDataPoints) removeData();"
    "dataPlot.data.labels.push(label);"
    "dataPlot.data.datasets[0].data.push(data);"
    "dataPlot.update();"
  "}"
  "function ci() {"
    "dataPlot = new Chart(eb('p'), {"
      "type: 'line',"
      "data: {"
        "labels: [],"
        "datasets: [{"
          "data: [],"
          "label: 'Pressure (Pa)',"
          "borderColor: '#3e95cd',"
          "fill: false"
        "}]"
      "}"
    "});"
  "}"
  "wl(ci);"
  ;